apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: controller-manager-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/instance: controller-manager-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: lightspeed-operator
    control-plane: controller-manager
  name: lightspeed-operator-controller-manager-service
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
